name: Build Branch

on: 
  push:
    branches: ['*']

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v2
      name: Checkout
    - uses: actions/setup-go@v2
      name: "Setup Go"
      with:
        go-version: 1.16

    - name: Build and Test
      run: go test -v ./... && go run -v ./...
      env:
        GO111MODULE: "on"

    - name: Codecov
      run: bash <(curl -s https://codecov.io/bash)
      continue-on-error: true
