name: Go

on:
  push:
    tags: ['*']

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
      
    - name: Test
      run: go test -v ./...
      env:
        GO111MODULE: "on"

    - name: Linux Build
      run: go build -v ./... && tar cvzf redump-linux.tar.gz
      env:
        GO111MODULE: "on"
        GOOS: "linux"
      
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          redump-darwin.tar.gz
          redump-linux.tar.gz
          redump-windows.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
